### ISSUE TITLE
Outlet switches not controllable

### ISSUE THREAD

**Issue by ifuchs** [magico13/ha-emporia-vue#117]
I updated to the latest version of the integration and I am no longer able to control the outlet switches. I can see power utilization but the devices do not show up as switches. Did we lose this functionality or am I missing something?

**Comment by magico13** [comment]
There was an issue with that on the previous version but the latest 0.7 version should be working properly

**Comment by ifuchs** [comment]
I just checked and my upgrade to 0.7.3 from 0.7.2 didn’t take for some reason. I tried again and after restarting HA, HACS still shows that there is an upgrade to 0.7.3. Could this be related to upgrading to the lasteset HA? How to get the latest version of Emporia Vue integration installed?

**Comment by ifuchs** [comment]
Checked the log and there appear to be 50+ repetitions of "Backing off async download" followed by "giving up async download ..." followed by "download was not completed, timeout, got an unexpected keyword argument 'loop'

**Comment by ifuchs** [comment]
@magico13 I did a manual install of 0.7.3 and the issue is resolved. Thanks.
