### ISSUE TITLE
Could not authenticate with Emporia API

### ISSUE THREAD

**Issue by hamradiovoip** [magico13/ha-emporia-vue#309]
Hi, I did an update of Home Assistant yesterday and now it will not connect to Emporia Vue servers/cloud.  I removed the integration and re-add it but I'm not sure where to make sure the password is OK.  Thanks.

Core 2024.9.1
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240906.0

This error originated from a custom integration.

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:97
integration: Emporia Vue (documentation, issues)
First occurred: 21:41:13 (1 occurrences)
Last logged: 21:41:13

Could not authenticate with Emporia API

**Comment by KA4HRE** [comment]
Same here...

Core 2024.9.1
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240906.0

This error originated from a custom integration.

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:97
integration: Emporia Vue (documentation, issues)
First occurred: September 8, 2024 at 5:41:51 AM (3 occurrences)
Last logged: 12:45:02 PM

Could not authenticate with Emporia API

**Comment by ghuserguy** [comment]
Same for me.  New install stuck at auth:
Core
2024.9.1
Supervisor
2024.09.1
Operating System
13.1
Frontend
20240906.0
Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:76
integration: emporia_vue ([documentation](https://github.com/magico13/ha-emporia-vue), [issues](https://github.com/magico13/ha-emporia-vue/issues))
First occurred: 10:02:27 PM (1 occurrences)
Last logged: 10:02:27 PM

**Comment by linit01** [comment]
Hopefully this is fixed soon, im on the same boat here.

**Comment by hamradiovoip** [comment]
There was a update yesterday. It didn't fix it. I'll try to look through the code and see what might be going on.

**Comment by KA4HRE** [comment]
Mine is working now with these versions.

Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Comment by hamradiovoip** [comment]
Still not working. Any ideas?
