### ISSUE TITLE
Which values to use for home energy monitoring in HA

### ISSUE THREAD

**Issue by southwestflavorz** [magico13/ha-emporia-vue#81]
I have both the Emporia Vue 2 and the utility connect, but I am uncertain which sensors I should use for configuring the home energy monitor within Home assistant. Can you point me in the right direction?

**Comment by magico13** [comment]
Use the 1D sensor for whichever one you want to use the data from. The sensor should look be named something like `Power Home 1,2,3 1D`. If you have solar you'll want to also use the two From and To Grid sensors in the appropriate place in the energy dashboard setup.

**Comment by southwestflavorz** [comment]
Does this look right:

![image](https://user-images.githubusercontent.com/4965670/131929568-0c4d677f-7399-493d-89b7-249dfd8d5863.png)

**Comment by magico13** [comment]
I think you might want to use MainsFromGrid under the "Grid consumption" section since you've got solar panels but otherwise I think it looks right!

**Comment by southwestflavorz** [comment]
I tried that, and nothing populated over 2 days. Solar shows up as blank too. My solar numbers are negative, not sure if that's affecting thing.s

**Comment by magico13** [comment]
You might be getting bitten by #67 which will hopefully start working with HA 2021.9 and the next update of this integration. I might need to flip the solar numbers to positive, I was wondering about that earlier today actually.

In the mean time you can try to use just the `Main Usage 1,2,3` and that should at least populate some data.

**Comment by southwestflavorz** [comment]
Just upgraded to the latest version, and now everything seems to be out of wack:

![image](https://user-images.githubusercontent.com/4965670/131934273-170717a4-ae52-4a1a-967b-37c1fe44976c.png)

**Comment by magico13** [comment]
Yeah it's a weird situation, the current release doesn't work on 2021.9 so you have to reinstall the integration from master. But the master version doesn't work on 2021.8.

**Comment by magico13** [comment]
In HACS select the reinstall option and then select "master" as the version
![image](https://user-images.githubusercontent.com/5289685/131935374-3fbbd100-67ac-4ad8-bf5a-87c1d0df0d1a.png)

**Comment by wildcard5** [comment]
Hi
I added all the single circuit entities (1D) into the Electricity grid so that it would add them all up and give me total consumption as the total grid to mains would not show any values.
I had to invert my solar production (in the YAML custom config) as it didn't like negative values and this seems to work as it's now calculating correctly.
I don't know about returned to grid as its cloudy at the moment and i'm consuming all solar at the moment.
I can show my setup later when i get in from work if anyone need it

Thanks again for this intergration

**Comment by skynet01** [comment]
Also the 1M sensors work as HA uses last updated time stamp to get the data.

**Comment by magico13** [comment]
The 1M sensors update less frequently so that's why I'd avoid using them. Those update hourly, 1D is updated every 15 minutes from the API, but I also integrate the 1Min sensor data into them so HA thinks they update once a minute. That higher update frequency *should* translate into more accurate data in the energy dashboard so that's why I tend to recommend the 1D over 1M sensors for it.

**Comment by BtrieveBill** [comment]
I am also struggling with getting this working, so any advice you can provide is appreciated.  I have set up the 1D counters, but do get an error when I do that here:
![image](https://user-images.githubusercontent.com/89939779/132394684-6de4d679-def7-495a-9730-707d88a3b354.png)
When I go to the Energy dashboard, the numbers are wacky:
![image](https://user-images.githubusercontent.com/89939779/132394724-5c5f1800-21cb-44f2-bab5-5e35d471ec18.png)
While I certainly use a lot of electricity, I am NOT pulling 200 kWh per hour at noon-time.  I suspect that HASS is expecting some setting that is missing, and therefore instead of calculating a difference, it keeps adding up the data over and over again???

**Comment by magico13** [comment]
@BtrieveBill make sure you're on version 0.7.0 if you're on Home Assistant 2021.9.x. That version uses the `total_increasing` state class and should fix that problem.

**Comment by BtrieveBill** [comment]
I saw that since the above comments were posted, formal updates for HACS and Vue were available.  Just did that, and the total_increasing issue indeed went away.  Still shows my house using 200 kW per hour, though, which is wrong.  However, I read (somewhere) that you had to wait two hours for the data to feed through properly, so I've been waiting.  Or do you think I have to delete everything and start over?  (I spent a LOT of time renaming my sensor values, since there are 3 for each CT, and I have two Vues with 27 monitored circuits and 4 plug/switch monitors. I'd really like to not have to go through THAT again.)

**Comment by magico13** [comment]
You should just have to wait and it should start calculating correctly with future data, assuming that's all the issue was. The total will definitely be out of whack because of the old data but hopefully new data comes in correctly. Since 2021.9 I've seen the energy dashboard line up almost exact with the data from the app, maybe a difference of a .1 kWh for the day.

**Comment by thatneat** [comment]
I'm on Home Assistant 2021.9.3 and Emporia Vue v0.7.0, and I'm having an issue a lot like this but for individual circuits/devices. I'm using the 1D data for individual circuits appears to be cumulative for the day:

![image](https://user-images.githubusercontent.com/3341011/132551070-ef90d75c-fee1-4899-a36a-a29bbea8a0f7.png)

Is there something I need to change in my configuration to get the rate to be in there properly?

**Comment by ekauzlar** [comment]
Hi,

I'm also trying to get this integration working in HA's energy view.  It almost seems like it's x1000 off for some reason.

Looking at the entity values it seems correct:
![image](https://user-images.githubusercontent.com/9103168/133724147-b7801211-75df-4761-91e1-8e13a0dc8f59.png)

But in the Energy section I'm getting this:
![image](https://user-images.githubusercontent.com/9103168/133724326-d8f68fdb-e509-490a-80bb-701843f9c434.png)

Any insight would be helpful!

**Comment by powdahound** [comment]
@dekesone Has the setup above been working well for you? I'm just getting one of the Utility Connect devices set up and wondering if it's worth trying to connect to the HA Energy dashboard or not.
